// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrhrjwxccyaxskbrgcxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyaHJqd3hjY3lheHNrYnJnY3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjI0MDgsImV4cCI6MjA3MDU5ODQwOH0.J5zOcxtSqHhdAvJ7VtaGYNFQ9hFwfIkaXXa3rPrgV3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});